### ISSUE TITLE
QML module not found (Ros)

### ISSUE THREAD

**Issue by KermitLee** [severin-lemaignan/ros-qml-plugin#5]
I followed the README through it all. '#include<ros/ros.h>' is work in cpp, but 'import Ros 1.0' isn't work.
It shows that QML module not found (Ros). It also failed to compile successfully.
![image](https://user-images.githubusercontent.com/17827496/89409852-4a7b2d80-d755-11ea-85c8-924b420f4b38.png)

**Comment by ljoh217** [comment]
Heya, I'm experiencing the same problem! I haven't solved it yet.

**Comment by KermitLee** [comment]
> Heya, I'm experiencing the same problem! I haven't solved it yet.

I've solved it. You will need to copy the Ros folder under the ' /usr/lib/x86_64-linux-gnu/qt5/qml/Ros' path to the path where you installed Qt. 
In my computer environment such a command  `sudo cp -R /usr/lib/x86_64-linux-gnu/qt5/qml/Ros ~/Qt5.12.9/5.12.9/gcc_64/qml/` can be solved .
